import React from 'react';
import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="min-h-screen bg-bg-base text-ink-primary font-sans">
      <nav className="w-full max-w-4xl mx-auto px-6 py-6 flex items-center justify-between border-b border-border">
        <Link to="/" className="font-semibold text-xl tracking-tight">Agent47</Link>
        <Link to="/" className="text-sm text-ink-secondary hover:text-ink-primary">Back to Home</Link>
      </nav>
      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-semibold mb-8 tracking-tight">Terms of Service</h1>
        <div className="space-y-6 text-[15px] leading-relaxed text-ink-secondary font-light">
          <p><strong>Last Updated: {new Date().toLocaleDateString()}</strong></p>
          <p>Please read these terms carefully before using Agent47 ("us", "we", or "our").</p>
          
          <h2 className="text-xl font-semibold text-ink-primary mt-8 mb-4">1. Acceptance of Terms</h2>
          <p>By accessing or using Agent47, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.</p>
          
          <h2 className="text-xl font-semibold text-ink-primary mt-8 mb-4">2. Description of Service</h2>
          <p>Agent47 is an experimental AI orchestration layer built for the Google GenAI Hackathon. It provides an interface to interact with your Google Workspace data via Google's APIs.</p>

          <h2 className="text-xl font-semibold text-ink-primary mt-8 mb-4">3. Accuracy of AI Output</h2>
          <p>The service utilizes generative artificial intelligence. Output generated by the AI may occasionally be inaccurate, incomplete, or misleading. You are solely responsible for reviewing and verifying the accuracy of any generated emails, calendar events, or document summaries before acting upon them.</p>

          <h2 className="text-xl font-semibold text-ink-primary mt-8 mb-4">4. Limitation of Liability</h2>
          <p>In no event shall Agent47, its developers, or its partners be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
        </div>
      </main>
    </div>
  );
}
