import React from 'react';
import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="min-h-screen relative bg-bg-base text-ink-primary font-sans overflow-x-hidden">
      {/* Ambient Light Orbs */}
      <div className="fixed top-[-10%] left-[-10%] w-[500px] h-[500px] bg-accent/20 rounded-full blur-[120px] pointer-events-none mix-blend-multiply" />
      <div className="fixed top-[20%] right-[-10%] w-[600px] h-[600px] bg-accent-dim/15 rounded-full blur-[150px] pointer-events-none mix-blend-multiply" />
      
      <header className="sticky top-0 z-50 w-full bg-white/60 backdrop-blur-xl border-b border-white/60 shadow-sm">
        <nav className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
          <Link to="/" className="flex items-center gap-3 transition-transform hover:scale-105 group">
            <div className="h-9 w-9 bg-white rounded-[10px] p-0.5 border border-white/80 shadow-sm flex items-center justify-center">
              <img src="/bot.png" alt="Agent47 Logo" className="h-[90%] w-[90%] object-contain" />
            </div>
            <span className="text-xl font-bold tracking-tight text-ink-primary font-display">Agent47</span>
          </Link>
          <Link to="/" className="text-sm font-semibold text-ink-secondary hover:text-accent transition-colors">Back to Home</Link>
        </nav>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16 relative z-10 animate-fade-in-up">
        <h1 className="text-5xl font-bold mb-10 tracking-tighter font-display">Terms of Service</h1>
        <div className="space-y-6 text-[16px] leading-relaxed text-ink-secondary font-medium bg-white/60 backdrop-blur-2xl border border-white/60 p-8 rounded-[32px] shadow-sm">
          <p><strong>Last Updated: {new Date().toLocaleDateString()}</strong></p>
          <p>Please read these terms carefully before using Agent47 ("us", "we", or "our").</p>
          
          <h2 className="text-xl font-semibold text-ink-primary mt-8 mb-4">1. Acceptance of Terms</h2>
          <p>By accessing or using Agent47, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.</p>
          
          <h2 className="text-xl font-semibold text-ink-primary mt-8 mb-4">2. Description of Service</h2>
          <p>Agent47 is an experimental AI orchestration layer built for the Google GenAI Hackathon. It provides an interface to interact with your Google Workspace data via Google's APIs.</p>

          <h2 className="text-xl font-semibold text-ink-primary mt-8 mb-4">3. Accuracy of AI Output</h2>
          <p>The service utilizes generative artificial intelligence. Output generated by the AI may occasionally be inaccurate, incomplete, or misleading. You are solely responsible for reviewing and verifying the accuracy of any generated emails, calendar events, or document summaries before acting upon them.</p>

          <h2 className="text-xl font-semibold text-ink-primary mt-8 mb-4">4. Limitation of Liability</h2>
          <p>In no event shall Agent47, its developers, or its partners be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
        </div>
      </main>
    </div>
  );
}
